//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Examar.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD AN ELEMENT.
        /// </summary>
        public static string Creator_Exam_AddElement {
            get {
                return ResourceManager.GetString("Creator_Exam_AddElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Creator_Exam_Cancel {
            get {
                return ResourceManager.GetString("Creator_Exam_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT DETAILS.
        /// </summary>
        public static string Creator_Exam_EditDetails {
            get {
                return ResourceManager.GetString("Creator_Exam_EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Creator_Exam_Element_Preview {
            get {
                return ResourceManager.GetString("Creator_Exam_Element_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Creator_Exam_Element_Type {
            get {
                return ResourceManager.GetString("Creator_Exam_Element_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELEMENTS.
        /// </summary>
        public static string Creator_Exam_Elements {
            get {
                return ResourceManager.GetString("Creator_Exam_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        public static string Creator_Exam_Export {
            get {
                return ResourceManager.GetString("Creator_Exam_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE PATH.
        /// </summary>
        public static string Creator_Exam_FilePath {
            get {
                return ResourceManager.GetString("Creator_Exam_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Creator_Exam_Save {
            get {
                return ResourceManager.GetString("Creator_Exam_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        public static string Creator_Exam_Title {
            get {
                return ResourceManager.GetString("Creator_Exam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create An Exam.
        /// </summary>
        public static string Creator_Header_Name {
            get {
                return ResourceManager.GetString("Creator_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit The Element.
        /// </summary>
        public static string ElementEditor_Header_Name {
            get {
                return ResourceManager.GetString("ElementEditor_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explains the task..
        /// </summary>
        public static string Elements_Default_Instruction_Description {
            get {
                return ResourceManager.GetString("Elements_Default_Instruction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of the instruction..
        /// </summary>
        public static string Elements_Default_Instruction_FieldDescription {
            get {
                return ResourceManager.GetString("Elements_Default_Instruction_FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Elements_Default_Instruction_FieldName {
            get {
                return ResourceManager.GetString("Elements_Default_Instruction_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Elements_Default_Instruction_Name {
            get {
                return ResourceManager.GetString("Elements_Default_Instruction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renders LaTeX content..
        /// </summary>
        public static string Elements_Default_LaTeX_Description {
            get {
                return ResourceManager.GetString("Elements_Default_LaTeX_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LaTeX code..
        /// </summary>
        public static string Elements_Default_LaTeX_FieldDescription {
            get {
                return ResourceManager.GetString("Elements_Default_LaTeX_FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Elements_Default_LaTeX_FieldName {
            get {
                return ResourceManager.GetString("Elements_Default_LaTeX_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaTeX.
        /// </summary>
        public static string Elements_Default_LaTeX_Name {
            get {
                return ResourceManager.GetString("Elements_Default_LaTeX_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves blank space..
        /// </summary>
        public static string Elements_Default_Space_Description {
            get {
                return ResourceManager.GetString("Elements_Default_Space_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of blank space (in inches)..
        /// </summary>
        public static string Elements_Default_Space_FieldDescription {
            get {
                return ResourceManager.GetString("Elements_Default_Space_FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Elements_Default_Space_FieldName {
            get {
                return ResourceManager.GetString("Elements_Default_Space_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Elements_Default_Space_Name {
            get {
                return ResourceManager.GetString("Elements_Default_Space_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays some text..
        /// </summary>
        public static string Elements_Default_TextBlock_Description {
            get {
                return ResourceManager.GetString("Elements_Default_TextBlock_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of the text block..
        /// </summary>
        public static string Elements_Default_TextBlock_FieldDescription {
            get {
                return ResourceManager.GetString("Elements_Default_TextBlock_FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Elements_Default_TextBlock_FieldName {
            get {
                return ResourceManager.GetString("Elements_Default_TextBlock_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Block.
        /// </summary>
        public static string Elements_Default_TextBlock_Name {
            get {
                return ResourceManager.GetString("Elements_Default_TextBlock_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives space for the answer..
        /// </summary>
        public static string Elements_Default_WritingArea_Description {
            get {
                return ResourceManager.GetString("Elements_Default_WritingArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of lines for the answer..
        /// </summary>
        public static string Elements_Default_WritingArea_FieldDescription {
            get {
                return ResourceManager.GetString("Elements_Default_WritingArea_FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Elements_Default_WritingArea_FieldName {
            get {
                return ResourceManager.GetString("Elements_Default_WritingArea_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Area.
        /// </summary>
        public static string Elements_Default_WritingArea_Name {
            get {
                return ResourceManager.GetString("Elements_Default_WritingArea_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select An Element.
        /// </summary>
        public static string ElementSelector_Header_Name {
            get {
                return ResourceManager.GetString("ElementSelector_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE AN EXAM.
        /// </summary>
        public static string Main_SideBar_ButtonCreateExam {
            get {
                return ResourceManager.GetString("Main_SideBar_ButtonCreateExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string Main_SideBar_HeaderMenu {
            get {
                return ResourceManager.GetString("Main_SideBar_HeaderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PINNED.
        /// </summary>
        public static string Main_SideBar_HeaderPinned {
            get {
                return ResourceManager.GetString("Main_SideBar_HeaderPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        public static string Main_SideBar_MenuAddons {
            get {
                return ResourceManager.GetString("Main_SideBar_MenuAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string Main_SideBar_MenuExams {
            get {
                return ResourceManager.GetString("Main_SideBar_MenuExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Main_SideBar_MenuHome {
            get {
                return ResourceManager.GetString("Main_SideBar_MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_SideBar_MenuSettings {
            get {
                return ResourceManager.GetString("Main_SideBar_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pinned..
        /// </summary>
        public static string Main_SideBar_NoPinned {
            get {
                return ResourceManager.GetString("Main_SideBar_NoPinned", resourceCulture);
            }
        }
    }
}
